### ISSUE TITLE
GDAL support files not found

### ISSUE THREAD

**Issue by ajolma** [shawnlaffan/perl-alien-gdal#12]
This build fails partly because gcs.csv is not found

http://www.cpantesters.org/cpan/report/843a86c0-4aca-11e8-b987-a8aeba13b3a2

Would there be a way to get the path to the installed files to set it to GDAL_DATA for BSD?
Under Linux the path is something like /usr/local/lib/x86_64-linux-gnu/perl/5.22.1/auto/share/dist/Alien-gdal/share/gdal/ and GDAL finds the support files.

**Comment by shawnlaffan** [comment]
Assuming the files are being installed properly (I have not checked yet), it should be possible to use a path relative to the dist_dir or bin_dir.  
https://metacpan.org/pod/Alien::Base#dist_dir

**Comment by shawnlaffan** [comment]
Windows installs them in a relative dir, so I assume it should work on BSD.  

We could perhaps add a method to Alien::gdal with the code below, perhaps using Path::Tiny instead of simple string concatenation.

```perl
my $alien = Alien::gdal->new;
my $path = $alien->bin_dir . '/../share/gdal';
```

**Comment by shawnlaffan** [comment]
Make that 
```perl
my $alien = Alien::gdal->new;
my $path = $alien->dist_dir . '/share/gdal';
```

I've added a method to the code and am running a test build now.

**Comment by shawnlaffan** [comment]
Updates are now on CPAN:  https://metacpan.org/release/SLAFFAN/Alien-gdal-1.05

**Comment by shawnlaffan** [comment]
We could also get this from the pkg config file as a more general solution.

```bash
CONFIG_VERSION=2.2.4
CONFIG_INST_PREFIX=C:/STRAWB~1/perl/site/lib/auto/share/dist/Alien-gdal
CONFIG_INST_LIBS=-LC:/STRAWB~1/perl/site/lib/auto/share/dist/Alien-gdal/lib -lgdal  -lodbc32 -lodbccp32 -lgif -ljpeg -lpng -Lc:/STRAWB~1/c/lib -lpq -lz -lpthread  -lws2_32 -lpsapi              -liconv  -L/../../lib -lxml2 -L/../../lib -lz -L/../../lib -llzma -lws2_32   
CONFIG_INST_CFLAGS=-IC:/STRAWB~1/perl/site/lib/auto/share/dist/Alien-gdal/include
CONFIG_INST_DATA=C:/STRAWB~1/perl/site/lib/auto/share/dist/Alien-gdal/share/gdal/data
prefix=${CONFIG_INST_PREFIX}
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${exec_prefix}/include
datadir=${CONFIG_INST_DATA}
Name: libgdal
Description: Geospatial Data Abstraction Library
Version: ${CONFIG_VERSION}
Libs: ${CONFIG_INST_LIBS}
Cflags: ${CONFIG_INST_CFLAGS}
```

**Comment by shawnlaffan** [comment]
cpan testers is largely red.  http://matrix.cpantesters.org/?dist=Alien-gdal%201.07

Looks like the paths are not being set, but this should be done by Alien::Test?

**Comment by shawnlaffan** [comment]
Updates tagged with wrong issue in f758b64e8a8c58edafe53918ce839d2579b8ae2b, 8b540a3985aa0a8af985a8a8d81f2bc049edafa9 and ae2a55a5dcca1a1f2fed271356f12067751d299d

(actually these should have been under their own issue)

**Comment by ajolma** [comment]
Here are some GNU/Linux systems having this problem: http://www.cpantesters.org/cpan/report/104da2cc-508f-11e8-a607-92445490f1e0 
I haven't been able to reproduce the error so far. I have now a travis build of Geo-GDAL-FFI that uses Alien::gdal built GDAL but that shows no errors.

**Comment by shawnlaffan** [comment]
version 1.07 should fix that issue, but it's failing for other reasons.  1.08_001 passes for more systems, but fails for several it was previously passing.  

I suspect it is something to do with the library paths and how they are handled under testing (see issue #10).  I am thinking I will mark the compilation test as todo on all platforms so Geo::GDAL::FFI gets to work with the installed paths.  The compilation test should probably also use FFI given that's how the gdal libs are accessed, but I'll need some assistance to do that.

**Comment by shawnlaffan** [comment]
And the fix to get the GDAL_DATA env var set should be something like this, but perhaps with some error checking and localisation:

```perl
$ENV{GDAL_DATA} ||= Alien::gdal->data_dir;
```

Let me know if it is better set in Alien::gdal.

**Comment by shawnlaffan** [comment]
Looks like cygwin installs the support files under the gdal package, not the libgdal package, so there is no guarantee of a data dir.  

This report uses a system install, and cannot find the data dir:

http://www.cpantesters.org/cpan/report/cdc1c122-3efd-1015-bc30-23b394f39f87

**Comment by ajolma** [comment]
The problem with using PkgConfig seems to be that GDAL makes a faulty gdal.pc (I reported this issue a minute ago).

**Comment by shawnlaffan** [comment]
Good catch.  I had not noticed that issue.

**Comment by shawnlaffan** [comment]
On the topic of config files, the alienfile has a sub to append the CONFIG_DEP_LIBS from gdal-config to CONFIG_INST_LIBS in gdal.pc.  

Should that also be added?

**Comment by ajolma** [comment]
Here's an example of GDAL support files not found although the GDAL_DATA is set to (probably) correct location (see the FYI: GDAL_DATA=xxx; the datadir is obtained from gdal.pc stripping the faulty '/data' from the end):
http://www.cpantesters.org/cpan/report/09d864ba-59b6-11e8-9024-a6dde193ab15
Is the data file installation failing?

**Comment by shawnlaffan** [comment]
The data dir test is marked as TODO, but that machine passed the test so the directory exists.    
http://www.cpantesters.org/cpan/report/953500d2-58fc-11e8-b3af-a05b59596cfe

Whether the files are in it is another question.  Maybe the Geo::GDAL::FFI test should diag a file listing.  

The Cygwin failure is likely because the share files are installed via another package, and that machine appears not to have it.
http://www.cpantesters.org/cpan/report/d4a5c24c-4ae3-1015-b5a8-c39a94f39f87

**Comment by ajolma** [comment]
This is an interesting example of how finding GDAL data fails:
http://www.cpantesters.org/cpan/report/4802a014-5fee-11e8-8649-9a118c28008b
GDAL_DATA is set (in FFI.pm) like this
```
my $pc = PkgConfig->find('gdal');
my $dir = $pc->get_var('datadir');
$dir =~ s/\/data$//;
CPLSetConfigOption(GDAL_DATA => $dir);
```
(/data is removed due to a GDAL bug, which is not yet fixed in releases)

**Comment by shawnlaffan** [comment]
I think that case is because the tester is not doing the final install for Alien::gdal. The gdal.pc file points to the final install location, but it is not yet there.  

This tester seems to be using the blib dirs directly, as per the ```@INC``` listing at the end of the report.  Extract below.

A workaround for testing Geo::GDAL::FFI would be to check if the gdal.pc file is under a blib dir, and $ENV{AUTOMATED_TESTING} is true, and adjust the path.  Alien::gdal could use the same logic to skip the test (currently marked as TODO due to failures like this).  


```
@INC:
   # first 20 or so entries elided
    /home/njh/.cpan/build/Alien-FFI-0.19-0/blib/arch
    /home/njh/.cpan/build/Alien-FFI-0.19-0/blib/lib
    /home/njh/.cpan/build/Alien-gdal-1.09-0/blib/arch
    /home/njh/.cpan/build/Alien-gdal-1.09-0/blib/lib
    ...
```

**Comment by shawnlaffan** [comment]
Even simpler might be to adapt the initial solution I noted when under testing, as I think the dist_dir method returns the actual path and not the one from gdal.pc.  It would also need to check whether Alien::gdal used a system or shared install.

```perl
#  untested 
my $alien = Alien::gdal->new;
my $path = get_gdal_data_dir();
if (!-d $path && $ENV{AUTOMATED_TESTING} && $alien->install_type eq 'share') {
    #  maybe also check for os=darwin
    $path = $alien->dist_dir . '/share/gdal';
}
...
```

**Comment by ajolma** [comment]
I decided that in Geo::GDAL::FFI I set GDAL_DATA only if gdal.pc is found and datadir from it exists - warning is issued if that is not the case. Tests requiring support files are skipped if GDAL_DATA is not set. I also fixed a small floating point issue. Hoping to get a nice all green results now from cpantesters!

**Comment by shawnlaffan** [comment]
That approach looks to have worked.

I'll think about adding it to the Alien::gdal data_dir method as a special case.

**Comment by shawnlaffan** [comment]
Looks like some raster drivers fail if the data dir cannot be located, so it might be better to fail rather than skip tests when it is not found?
shawnlaffan/biodiverse#699

**Comment by shawnlaffan** [comment]
I think this can be closed.  Geo::GDAL::FFI has a workaround in place, and has been working without issue for a while.
