### ISSUE TITLE
Problem installing Alien::gdal using both cpan and cpanm

### ISSUE THREAD

**Issue by mbarbeeDK** [shawnlaffan/perl-alien-gdal#20]
Newby in Perl. 
I installed Strawberry Perl Windows Server 2012. Trying to get Alien::gdal and Geo::GDAL::FFI modules installed for project work. Keep chasing down errors and missing components. 
- I have cgg.exe- installed for other software packages and with Strawberry. 
- Have mingw_64 installed but it looks like the configfiles or packages (?) are looking at mingw32. 
- Looks like the compiler is missing or not working/found according to the build log and the config log seems to point to a larger issue?
Another person tested a standalone install of Perl and the module installs with the same errors.

Searched a round a lot and cannot seem to find the problem replicated on a Windows machine. Is there a better method or step-wise process to get the GDAL tools into Perl??

Cheers,
MB

[build.log](https://github.com/shawnlaffan/biodiverse/files/6458225/build.log)

[config.log](https://github.com/shawnlaffan/biodiverse/files/6458222/config.log)

**Comment by shawnlaffan** [comment]
Thanks for the logs.  They're very helpful.  

It looks like you are hitting the issue that commit 2df453ad43dcded6badb932e66e67d51fb05540a was implemented to address.  

It's not yet in a cpan release but you can install it from github using 
```cpanm https://github.com/shawnlaffan/perl-alien-gdal.git```

I'll see if I can cut a new release in the next day or so.  

Shawn.

**Comment by mbarbeeDK** [comment]
Thanks Shawn! 
I will have to wait for CPAN to update its module list until tomorrow. It looks like it's still seeing 1.23.
-MB

**Comment by shawnlaffan** [comment]
Not a problem.  

You can install it for now using 

```cpanm Alien::gdal@1.24```

**Comment by shawnlaffan** [comment]
This should be fixed now, but please reopen if not.
