### ISSUE TITLE
cpan testers failures on BSD variants

### ISSUE THREAD

**Issue by shawnlaffan** [shawnlaffan/perl-alien-gdal#5]
http://matrix.cpantesters.org/?dist=Alien-gdal+1.03

Seems to be failing at the make stage (for those that get that far).  

Example fail:

```
Alien::Build::CommandSequence> + make | perl -ne 'BEGIN {$|=1; open our $log, q|>|, q|build.log|}; print qq|\n| if 0 == ($. % 100); print q|.|; print {$log} $_;' || cat build.log
make[1]: no target to make.
```

**Comment by shawnlaffan** [comment]
Seems unrelated to static builds (issue #6): http://www.cpantesters.org/cpan/report/b26b4d14-3d1d-11e8-9abe-a171f40b351c

**Comment by ajolma** [comment]
I just installed FreeBSD on a virtual machine on my laptop and it seems that freebsd make is not gnu make, which is needed. Gnu make is 'gmake' in freebsd.

**Comment by shawnlaffan** [comment]
One would expect the Alien system to pick this up?  If not then we can perhaps look at probing for which make is available. 

...OK, I think I worked it out.

**Comment by ajolma** [comment]
Works now in my freebsd environment.

**Comment by shawnlaffan** [comment]
Thanks Ari.  Looks like it's solved, but I'll wait for cpan testers to show green for the build stage before I close the ticket.

**Comment by shawnlaffan** [comment]
The gmake issue looks to be solved, but now it cannot find tiffio.h.

http://www.cpantesters.org/cpan/report/0903f568-3e0e-11e8-a1cf-bb670eaac09d
http://www.cpantesters.org/cpan/report/1b852154-3df4-11e8-9abe-a171f40b351c

**Comment by ajolma** [comment]
It may be a configure error in GDAL (let's see what Even has to say) but it could be bypassed by setting --with-libtiff=internal (I did not test this).

**Comment by shawnlaffan** [comment]
If it's a gdal configure issue then it's best fixed at the gdal end, but if it looks like it might take a while then we can bypass as you suggest.

**Comment by shawnlaffan** [comment]
Running a freebsd VM with gnome installed, I get the same issue for webp/decode.h.

Looks to be related to WebPDecodeRGB.  The compilation is finding WebPDecodeRGB but not the headers in /usr/local/include/webp.

As a data point, gdal does not find libtiff on this machine, despite it being on the system.  It thus does not hit the libtiff issue.

**Comment by ajolma** [comment]
In the tester reports it is confusing that the GDAL configure seems to find an external libtiff but then it fails to find the tiffio.h. I haven't been able to reproduce that.

**Comment by shawnlaffan** [comment]
It might be specific to that tester's environment.  Or it does have the headers and they are found in the configure phase, but not in the compile phase.

**Comment by ajolma** [comment]
Yes. I'd suggest to go ahead with --with-libtiff=internal also since the case of downloading and compiling GDAL is almost always only in a test situation - or should be.

**Comment by shawnlaffan** [comment]
I'll add the internal libtiff flag by default.

It won't solve the webp/decode.h on my VM which looks related.  I'll see if I can add some more feedback about search paths to the build process.

**Comment by shawnlaffan** [comment]
The libtiff issue seems fixed.  
This smoker does not flag any tiff issues:  http://www.cpantesters.org/cpan/report/0aae21a8-3f59-11e8-a1cf-bb670eaac09d

It then fails due to insufficient disk space.  I've opened issue #7 for that problem.


This smoker hits the webp issue, though, so it is perhaps worth disabling or using an internal version of that also. 
http://www.cpantesters.org/cpan/report/58d5691a-3f48-11e8-a1cf-bb670eaac09d

**Comment by shawnlaffan** [comment]
This one does not find jasper.h, so I suspect the include path is not working properly.  

http://www.cpantesters.org/cpan/report/d08e360c-3f44-11e8-9abe-a171f40b351c

**Comment by shawnlaffan** [comment]
The root cause could be that /usr/local/include is not in the paths.  https://forums.freebsd.org/threads/how-do-i-modify-the-include-path-during-a-source-install.26165/#post-146325

Need to test if /usr/local/include is in the search paths on BSD variants and add it if not.

**Comment by ajolma** [comment]
You can also add --with-local=dir (Include /usr/local or other local tree for INCLUDE/LIBS) to the GDAL configure.

**Comment by ajolma** [comment]
Now I hit a problem with the CAD driver: https://github.com/OSGeo/gdal/issues/432

**Comment by shawnlaffan** [comment]
My freebsd VM does not hit this issue.  It also does not have libopencad installed, though.

**Comment by shawnlaffan** [comment]
Just got a smoker back with the CAD issue.  http://www.cpantesters.org/cpan/report/d1ff2cba-418a-11e8-9abe-a171f40b351c

Will add --without-cpp11 to the BSD config options.

**Comment by shawnlaffan** [comment]
We have at least two passes for bsd on cpantesters.  http://matrix.cpantesters.org/?dist=Alien-gdal+1.03_010

This issue can probably be closed, but I'll wait a day or so to allow more reports to come in first.

**Comment by shawnlaffan** [comment]
cpantesters is all green for the bsd variants at version 1.3_010.  http://matrix.cpantesters.org/?dist=Alien-gdal+1.03_010
Closing this issue.
