### ISSUE TITLE
The build seems only static by default

### ISSUE THREAD

**Issue by ajolma** [shawnlaffan/perl-alien-gdal#6]
Errors here: http://matrix.cpantesters.org/?dist=Geo-GDAL-FFI are caused by Alien::gdal doing only a static build. I'm using

my $ffi = FFI::Platypus->new;
$ffi->lib(Alien::gdal->dynamic_libs );

to set up the FFI object. Setting it up for static libs seems not possible / difficult. Is there a way to allow dynamic libs by default in automated builds like cpantesters is doing?

**Comment by shawnlaffan** [comment]
Reading my comments in the alienfile, static builds were implemented to reduce log limit issues on travis.  However, since we are reducing the log size these days it should no longer be an issue.

**Comment by shawnlaffan** [comment]
Mark as fixed
