### ISSUE TITLE
cpan testers - use less disk space

### ISSUE THREAD

**Issue by shawnlaffan** [shawnlaffan/perl-alien-gdal#7]
Some CPAN smokers do not have sufficient disk space to compile GDAL, e.g. http://www.cpantesters.org/cpan/report/0aae21a8-3f59-11e8-a1cf-bb670eaac09d

It would be useful to detect this and fail gracefully.

Tasks, several of which should be limited to testing and smoking environments:
- [X] avoid static builds by default
- [X] Disable C++11 under automated testing
- [x] Run make clean under automated testing

We might skip these for now:
- [ ] Disable libtool under automated testing
- [ ] Build with minimised drivers under automated testing

**Comment by ajolma** [comment]
A minimal GDAL build would probably be good. https://trac.osgeo.org/gdal/wiki/BuildingOnUnixWithMinimizedDrivers

**Comment by shawnlaffan** [comment]
Good idea.  Once we have the bsd issues in #5 sorted out we can shift the testers build to a minimal one.

**Comment by shawnlaffan** [comment]
Just ran a successful build on freebsd, but the resultant tools in the blib folder are all 122MB in size (all 24 of them), while libgdal.a is ~360MB.  

The build itself is another 8-9 GB.  

This could be the root cause of several of the disk space issues.

**Comment by shawnlaffan** [comment]
Config log indicates that the freebsd cc linker supports shared libraries, but libtool does not.  This results in static builds on freebsd.

**Comment by shawnlaffan** [comment]
Possibly it's in the gdal config script: https://lists.freebsd.org/pipermail/freebsd-current/2013-March/040460.html

This check is likely disabling a shared compilation as it applies to freebsd 1, 10 and 11. 
```bash
    freebsd1*)
      ld_shlibs=no
      ;;
```

**Comment by ajolma** [comment]
~200 MB libgdal.so is made when using --without-libtool

**Comment by ajolma** [comment]
--without-cpp11 and --without-libtool seem to be required. In GDAL 2.2.4 the resulting so is ~140 MB.

**Comment by shawnlaffan** [comment]
I'll look into those arguments, although I would be surprised if freebsd does not support dynamic builds via libtool and so suspect it is an issue with the configure probe.

**Comment by shawnlaffan** [comment]
Updated configure patch in d33a8f187d10841878fcbe9f6de3f0c9541fbd6e

If it works then will send as a PR to the osgeo/gdal repo.

**Comment by shawnlaffan** [comment]
Further update in 6f7653115b125fd1761d7afdb19d16beb8ae9a9a

**Comment by shawnlaffan** [comment]
As of commit b2f988df6eb08dfb991cc8ab3ed3154b2cf2735d, the freebsd sizes are 130 MB for the blib dir and 782 MB for the _alien dir.  

On Ubuntu they are 97 MB and 596 MB, respectively.

**Comment by shawnlaffan** [comment]
gdal has updated its libtools files so the bsd patch will not be needed for future releases.  
https://github.com/OSGeo/gdal/commit/70bbca9ed27af6eb690e05c0e5434b27b1d89631

**Comment by shawnlaffan** [comment]
Minimal drivers pass on linux/osx:  https://travis-ci.org/shawnlaffan/perl-alien-gdal/builds/368425537
But fail on windows:  https://ci.appveyor.com/project/shawnlaffan/perl-alien-gdal/build/1.0.91

I get the same error on my own system.

**Comment by shawnlaffan** [comment]
Looks like many of the files listed in the failing ar command do not exist.  Could be a windows specific build issue.

**Comment by shawnlaffan** [comment]
At least the minimal driver approach works under freebsd.  The directory sizes are slightly smaller than otherwise.  blib is ~83MB, _alien is ~760MB.

**Comment by shawnlaffan** [comment]
The alienfile make clean step reduces the size of the build artefacts.  Under windows this leaves an _alien dir of ~300MB, so less than half of the previous size.  More could still be done, but probably best under the aegis of Alien::Build.  

Peak build size is now somewhere in the region of 700-900 MB.  Final size is about half that after make clean.

Alien::gdal 1.04 contains these changes and has just been released to CPAN.  

@eserte - these file sizes might now be small enough for you to re-enable your CPAN smokers for this distro (per https://www.nntp.perl.org/group/perl.cpan.testers.discuss/2018/04/msg4279.html ).

**Comment by shawnlaffan** [comment]
CPAN testers is coming up green.  The one failure so far appears to be due to a lack of memory.  

Marking issue as closed, but it can be re-opened if need be.

http://matrix.cpantesters.org/?dist=Alien-gdal%201.04

**Comment by eserte** [comment]
OK, I enabled Alien-gdal on my smokers.

**Comment by shawnlaffan** [comment]
Thanks @eserte
